version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installation started on $(date)"
      # To install dev dependencies even when NODE_ENV is set to production
      - npm config set production false
      - npm install -g serverless
      - npm install -g aws-sdk
      - npm ci
      - node -v
      - npm -v
      - sls -v
      - aws --version
  pre_build:
    commands:
      - echo "Lint and Test started on $(date)"
      - npm run lint
      - npm run test
  build:
    commands:
      - echo "Build started on $(date)"
      - npm config set production true
      - npm run build
  post_build:
    commands:
      - echo "Deployment started on $(date)"
      - npm run deploy

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'