service:
  name: boilerplate #TODO update service

# =========================================================================================
# Functions - Add function modules here
# =========================================================================================
functions:
  - ${file(src/api.yml)}

custom:
  defaults:
    stage: development
    region: us-east-1
    runtime: nodejs12.x
    memorySize: 256
    timeout: 10

# Local Stage Config
  local:
    logLevel: debug
    timeout: 10
    memorySize: 256
    logRetentionInDays: 1

  # Development Stage Config
  development:
    logLevel: debug
    timeout: 30
    memorySize: 256
    logRetentionInDays: 1

  # Staging Stage Config
  staging:
    logLevel: debug
    timeout: 30
    memorySize: 256
    logRetentionInDays: 7

  # Production Stage Config
  production:
    logLevel: info
    timeout: 30
    memorySize: 512
    logRetentionInDays: 90

  stages:
    - local
    - development
    - staging
    - production

  serverless-offline:
    httpPort: 9090
    apiKey: my-api-key
    noPrependStageInUrl: true

  dynamodb:
    stages:
      - local
    start:
      port: 9000
      inMemory: false
      region: ${self:provider.region}
      migrate: true

  serverless-offline-sqs:
    autoCreate: true # create queue if not exists
    apiVersion: "2012-11-05"
    endpoint: http://0.0.0.0:9324
    region: ${self:custom.defaults.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

  s3:
    bucketName: ${self:service} #TODO update bucket name
    host: localhost
    port: 9010
    directory: ./.s3
    cors: false
    accessKeyId: S3RVER
    secretAccessKey: S3RVER

  apigwBinary:
    types:
      - "image/*"
      - "text/html"
      - "multipart/form-data"
      - "application/octet-stream"

provider:
  name: aws
  region: ${opt:region, self:custom.defaults.region}
  runtime: ${self:custom.defaults.runtime}
  stage: ${opt:stage, self:custom.defaults.stage}
  memorySize: ${self:custom.${self:provider.stage}.memorySize}
  timeout: ${self:custom.timeout}
  apiGateway:
    minimumCompressionSize: 0
    shouldStartNameWithService: true
  deploymentBucket:
    name: deploys
    serverSideEncryption: AES256
  deploymentPrefix: serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:custom.s3.bucketName}
  environment:
    NODE_ENV: ${self:provider.stage}
    LOG_LEVEL: ${self:custom.${self:provider.stage}.logLevel}

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-dynamodb-local
  - serverless-apigw-binary
  - serverless-offline-sqs
  - serverless-s3-local
  - serverless-offline

package:
  individually: true

resources:
  Resources:
    # --------------------------------------------------------------------------------
    # Dynamodb Table
    # --------------------------------------------------------------------------------
    DevDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # --------------------------------------------------------------------------------
    # S3 buckets
    # --------------------------------------------------------------------------------
    DevS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service} #TODO update bucket name
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
            - AllowedOrigins:
                - "*"
            - AllowedHeaders:
                - "*"

    # --------------------------------------------------------------------------------
    # SQS Queue
    # --------------------------------------------------------------------------------
    DevSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service} #TODO update sqs name
